AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  resourceful - little functions doing big things
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6

# More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
Resources:

  # NodeJS general purpose functions

  ApiSfAdapter00:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-sf-adapter-00/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Policies:
        - AWSStepFunctionsFullAccess
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /v1
            Method: post

  DynamoDb00:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dynamodb-00/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Policies:
        - AmazonDynamoDBFullAccess

  GpFunction00:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gpf-00/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x

  # Severless Application Repository functions

  S3Upload00:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:233054207705:applications/uploader
        SemanticVersion: 1.0.3
      Parameters: 
        destBucket: tradyr-file-storage-dev
      